%YAML:1.0
#camera_name: "Microsoft® LifeCam VX-2000"
camera_calib: "calibration_microsoft_vx2000.yml"   # Path is relative to this file location

# Marker to be tracked
marker_dictionary: 0
marker_id: 0
marker_length: 0.035

# Camera position
camera_top: 1
